version: "3.9"
services:
  ms-shopping:
    build: ms-shopping
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    restart: always

  ms-payment:
    build: ms-payment
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always